<?php echo $this->tag->form("index/edit/".$userid); 
// print_r($userid);

?>


<h2>Edit Details</h2>
    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField('username'); ?>
    </p>
    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->passwordField('email'); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("submit"); ?>
    </p>

</form>