<?php echo $this->tag->form("index/editblog/".$blogid);
// print_r($userid);

?>


<h2>Edit Blog Details</h2>
    <p>
        <label for="name">Blog Name:</label>
        <?php echo $this->tag->textField('blogname'); ?> 
        <label for="type">Blog Type:</label>
        <?php echo $this->tag->textField('blogtype'); ?>
        <label for="blog">Full Blog:</label>
        <?php echo $this->tag->textField('fullblog'); ?>
    </p>
    <p>
       
    </p>

    <p>
        <?php echo $this->tag->submitButton("Update"); ?>
    </p>

</form>