<?php echo $this->tag->form("login/register"); ?>


<h2>Login</h2>
    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->passwordField("password"); ?>
    </p>
   

    <p>
        <?php echo $this->tag->submitButton("login"); ?>
    </p>

</form>