
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="text-align:center">BLOG HOME</h1>
    <div style="text-align:center">
   <a href="dashboard"><h1 class="btn btn-primary">BLOG HOME</h1></a>
  </div>
  <?php foreach ($blogs as $blog) { ?>
    <form action='' method='post'><div class='row'>
    
            <div class='card shadow-sm col-4 '>
            <strong>Blog Pic:</strong>
            <?php echo $blog->pic ?>

                <img src='../../../public/nathan-da-silva-k-rKfqSm4L4-unsplash (1).jpg' alt='pic' width=''  height=''>
                <div></div>
              <div class='card-body '>
              
                  <strong>Blog Name:</strong>
                  
                  <?php echo $blog->blogname ?>
                <p class='card-text'><strong>Type:</strong>
                <?php echo $blog->blogtype ?>
              </p>
                
                <p><strong>Blog Text:</strong>
                <?php echo $blog->fullblog ?>
              </p>
                <div class='d-flex justify-content-between align-items-center'>
                <p><strong></strong>&nbsp;</p></a>
                  <button class='btn btn-primary' name='cart' value='' >Edit</button>
                </div>
              </div>
              
            </div>
            
          </div>
          <?php }?>
        </form>
       
        
</body>
</html>